#Request Parameters
uint8 ACTION_MOVE_ARM_TO=0
uint8 ACTION_MOVE_ARM_AND_BASE_TO=1
uint8 ACTION_MOVE_BASE=2

uint8 type
string goal_pose_name
geometry_msgs/PoseStamped goal_pose
string[] do_not_blow_up_list

---

#Response Parameters
bool result
