#Request params
uint8 MOVE_GROUP_ARM=0
uint8 MOVE_GROUP_GRIPPER=1
uint8 MOVE_GROUP_BASE=2
uint8 MOVE_GROUP_ARM_BASE=3

uint8 move_group
string goal_pose_name
geometry_msgs/PoseStamped goal
moveit_msgs/RobotState start_state
float32 max_movement_time

---

#Response
moveit_msgs/MotionPlanResponse plan


