#!/bin/bash
ROS_SBCL_PATH=`rospack find sbcl`
ROSLISP_PATH=`rospack find roslisp`
EXECUTIVE_PATH=`rospack find suturo_planning_executive`
if [ -z "$ROSLISP_PATH" ]; then
  echo "roslisp not found"
  exit 1
fi
if [ -n "$ROS_SBCL_PATH" ]; then
  SBCL=/scripts/run-sbcl.sh
else
  SBCL=sbcl
fi

ROSLISP_CURRENT_PACKAGE=suturo_planning_executive $SBCL --noinform --end-runtime-options --noprint --no-userinit --disable-debugger --load $ROSLISP_PATH/scripts/roslisp-sbcl-init --load $EXECUTIVE_PATH/scripts/compile.lisp --end-toplevel-options $*
